@startuml

class AAUOC {
    newLocation(l:Location): void
    newEvent(e:Event): void
    newPerson(p:Person): void
    informEvent(e:Event): void
    register(m:Member, e:Event): void

}
class Location {

}
class Event{

}
class Conference {

}
class BroadMeeting{
}

class Person {

}
class Member{

}

class BroadMember {

}

AAUOC o-- Event
AAUOC o-- Location
AAUOC o-- Person
Location -- Event
Event <|-- Conference
Event <|-- BroadMeeting
Person <|-- Member
Member <|-- BroadMember
Event -- Member
Person -- Conference
BroadMeeting -- BroadMember



@enduml