@startuml

class AAUOC {
    newLocation(l:Location): void
    newEvent(e:Event): void
    newPerson(p:Person): void
    informEvent(e:Event): void
    register(m:Member, e:Event): void

}
class Location {
    description: String
    address: String

}
class Event{
    date: Date
    description: String
    assign(l:Location): void

}
class Conference {
    max_attendees: Integer

}
class BroadMeeting{
}

class Person {
    name: String

}
class Member{

}

class BroadMember {

}

AAUOC o-- Event
AAUOC o-- Location
AAUOC o-- Person
Location -- Event
Event <|-- Conference
Event <|-- BroadMeeting
Person <|-- Member
Member <|-- BroadMember
Event -- Member
Person -- Conference
BroadMeeting -- BroadMember



@enduml